version: "3.9"

services:
  plexcache:
    build: .
    volumes:
      - /mnt/media:/media
      - /mnt/cache:/cache

    ports:
      - "4001:4001"
    networks:
      - printer
    working_dir: /app
    restart: unless-stopped

networks:
  printer:
    driver: bridge
    external: true
